server:
  port: 8083
  servlet:
    context-path: /order-service

spring:
  redis:
    host: 127.0.0.1
    port: 6379
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/subproject_nhom03_kttkpm14
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  # cloud config
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      name: eureka-config
      uri:
      - http://localhost:8888

resilience4j:
  # retry
  retry:
    instances:
      basic:
        maxAttempts: 3
        waitDuration: 2s
        
  # ratelimiter
  ratelimiter:
    instances:
      basic:
        limitForPeriod: 2
        limitRefreshPeriod: 3s
        timeoutDuration: 1s



